// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmJELygB1NI4TZZpb5cneIXSs-TZthJxY',
    appId: '1:37823770721:web:74f86dd5543f0a300ffa20',
    messagingSenderId: '37823770721',
    projectId: 'ami-e-passbook',
    authDomain: 'ami-e-passbook.firebaseapp.com',
    storageBucket: 'ami-e-passbook.firebasestorage.app',
    measurementId: 'G-6E900CXRM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyI-UhDw7CGQ4n1iZyYbjaBM08FziVxc8',
    appId: '1:37823770721:android:d00b345bd4ca547f0ffa20',
    messagingSenderId: '37823770721',
    projectId: 'ami-e-passbook',
    storageBucket: 'ami-e-passbook.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ltWTptt4oCojACBPLYITqgeEFukxyFQ',
    appId: '1:37823770721:ios:be552ec70173e0af0ffa20',
    messagingSenderId: '37823770721',
    projectId: 'ami-e-passbook',
    storageBucket: 'ami-e-passbook.firebasestorage.app',
    iosBundleId: 'com.example.amiEPassbookApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ltWTptt4oCojACBPLYITqgeEFukxyFQ',
    appId: '1:37823770721:ios:be552ec70173e0af0ffa20',
    messagingSenderId: '37823770721',
    projectId: 'ami-e-passbook',
    storageBucket: 'ami-e-passbook.firebasestorage.app',
    iosBundleId: 'com.example.amiEPassbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmJELygB1NI4TZZpb5cneIXSs-TZthJxY',
    appId: '1:37823770721:web:441bd3b7ea2cdbdc0ffa20',
    messagingSenderId: '37823770721',
    projectId: 'ami-e-passbook',
    authDomain: 'ami-e-passbook.firebaseapp.com',
    storageBucket: 'ami-e-passbook.firebasestorage.app',
    measurementId: 'G-55CKR5KZTB',
  );
}
